# Generated by Django 4.0.4 on 2022-06-07 12:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=20)),
                ('long_name', models.CharField(max_length=225)),
                ('short_name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=255)),
                ('version', models.CharField(max_length=20, unique=True)),
                ('date_time', models.DateField(default=datetime.date.today)),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
            },
        ),
        migrations.CreateModel(
            name='DirectoryElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_code', models.CharField(max_length=20, null=True)),
                ('element_value', models.CharField(max_length=20, null=True)),
                ('directories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.directory')),
            ],
            options={
                'verbose_name': 'Элемент справочника',
                'verbose_name_plural': 'Элементы справочника',
            },
        ),
    ]
