# Generated by Django 4.0.4 on 2022-06-07 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='slug',
        ),
    ]
